### ISSUE TITLE
bipartmod needs the nodes of the two part of the network to be on different columns in the input

### ISSUE THREAD

**Issue by geeklhem** [stouffer/rgraph#9]
This behavior should be (at least) documented. 

Example: 

```
head women.dat -n 3
E5 Eleanor_Nye
Eleanor_Nye E8
Eleanor_Nye E6

bipartmod -f women.dat -p 2> /dev/null
1 8 55 0 55 55.000000 0.000000 55.000000 --- E1 E2 E6 E3 E4 E5 E8 E7
4 1 1 0 1 1.000000 0.000000 1.000000 --- Eleanor_Nye
9 6 33 0 33 33.000000 0.000000 33.000000 --- E9 E12 E10 E14 E13 E11
```

Whereas the correct behavior is obtained if the two part of the network are in their own column: 

```
$ head women.dat -n 3
Eleanor_Nye E5
Eleanor_Nye E8
Eleanor_Nye E6

$ bipartmod -f women.dat -p 2> /dev/null
11 6 33 0 33 33.000000 0.000000 33.000000 --- E9 E13 E14 E12 E10 E11
12 8 56 0 56 56.000000 0.000000 56.000000 --- E8 E4 E6 E5 E3 E1 E2 E7
```

**Comment by stouffer** [comment]
This is actually a feature not an issue since many people strictly use integer labels and the format of the file _is_ critically important. Namely, the following would be a four species pollination network:

```
1 1
1 2
2 2
```

I felt like it was already explicit when describing the format of the input data, but maybe a simple example would help make the point.
